import 'controller/iphone_14_pro_max_twentytwo_controller.dart';import 'models/iphone_14_pro_max_twentytwo_model.dart';import 'package:flutter/material.dart';import 'package:stafin_v1/core/app_export.dart';import 'package:stafin_v1/core/utils/validation_functions.dart';import 'package:stafin_v1/widgets/custom_button.dart';import 'package:stafin_v1/widgets/custom_drop_down.dart';import 'package:stafin_v1/widgets/custom_text_form_field.dart';
// ignore_for_file: must_be_immutable

// ignore_for_file: must_be_immutable
class Iphone14ProMaxTwentytwoPage extends StatelessWidget {GlobalKey<FormState> _formKey = GlobalKey<FormState>();

Iphone14ProMaxTwentytwoController controller = Get.put(Iphone14ProMaxTwentytwoController(Iphone14ProMaxTwentytwoModel().obs));

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(backgroundColor: Colors.transparent, body: Form(key: _formKey, autovalidateMode: AutovalidateMode.onUserInteraction, child: SingleChildScrollView(child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.start, children: [Padding(padding: getPadding(right: 10), child: Text("lbl_name".tr, overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: AppStyle.txtMontserratRomanRegular15)), CustomTextFormField(width: 339, focusNode: FocusNode(), controller: controller.group127Controller, hintText: "lbl_enter_name".tr, margin: getMargin(top: 6), variant: TextFormFieldVariant.OutlineBlack900_1, validator: (value) {if (!isText(value)) {return "Please enter valid text";} return null;}), Padding(padding: getPadding(top: 49, right: 10), child: Text("lbl_duration".tr, overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: AppStyle.txtMontserratRomanRegular15)), CustomDropDown(width: 339, focusNode: FocusNode(), icon: Container(margin: getMargin(left: 188, right: 26), child: CommonImageView(svgPath: ImageConstant.imgArrowdown)), hintText: "lbl_select_duration".tr, margin: getMargin(top: 7), items: controller.iphone14ProMaxTwentytwoModelObj.value.dropdownItemList, onChanged: (value) {controller.onSelected(value);}), Padding(padding: getPadding(top: 51, right: 10), child: Text("lbl_amount".tr, overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: AppStyle.txtMontserratRomanRegular15)), CustomTextFormField(width: 339, focusNode: FocusNode(), controller: controller.group126Controller, hintText: "lbl_enter_amount".tr, margin: getMargin(top: 6), variant: TextFormFieldVariant.OutlineBlack900_1, textInputAction: TextInputAction.done), CustomButton(width: 339, text: "lbl_subscribe".tr, margin: getMargin(top: 101), onTap: onTapSubscribe)]))))); } 
onTapSubscribe() { Get.toNamed(AppRoutes.iphone14ProMaxEighteenScreen); } 
 }
