import 'controller/iphone_14_pro_max_twenty_controller.dart';import 'models/iphone_14_pro_max_twenty_model.dart';import 'package:flutter/material.dart';import 'package:stafin_v1/core/app_export.dart';import 'package:stafin_v1/core/utils/validation_functions.dart';import 'package:stafin_v1/widgets/custom_button.dart';import 'package:stafin_v1/widgets/custom_text_form_field.dart';
// ignore_for_file: must_be_immutable

// ignore_for_file: must_be_immutable
class Iphone14ProMaxTwentyPage extends StatelessWidget {GlobalKey<FormState> _formKey = GlobalKey<FormState>();

Iphone14ProMaxTwentyController controller = Get.put(Iphone14ProMaxTwentyController(Iphone14ProMaxTwentyModel().obs));

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(backgroundColor: Colors.transparent, body: Form(key: _formKey, autovalidateMode: AutovalidateMode.onUserInteraction, child: SingleChildScrollView(child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.start, children: [Padding(padding: getPadding(right: 10), child: Text("lbl_brand".tr, overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: AppStyle.txtMontserratRomanRegular15)), Container(height: getVerticalSize(54.00), width: getHorizontalSize(339.00), margin: getMargin(top: 7), child: Stack(alignment: Alignment.centerLeft, children: [Align(alignment: Alignment.centerRight, child: Padding(padding: getPadding(left: 26, top: 22, right: 26, bottom: 22), child: CommonImageView(svgPath: ImageConstant.imgArrowdown, height: getVerticalSize(7.00), width: getHorizontalSize(13.00)))), CustomTextFormField(width: 339, focusNode: FocusNode(), controller: controller.groupFifteenController, hintText: "msg_type_select_brand".tr, variant: TextFormFieldVariant.OutlineBlack900_1, alignment: Alignment.centerLeft)])), Padding(padding: getPadding(top: 50, right: 10), child: Text("lbl_username".tr, overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: AppStyle.txtMontserratRomanRegular15)), CustomTextFormField(width: 339, focusNode: FocusNode(), controller: controller.groupFourteenController, hintText: "lbl_enter_username".tr, margin: getMargin(top: 6), variant: TextFormFieldVariant.OutlineBlack900_1, textInputAction: TextInputAction.done, validator: (value) {if (!isText(value)) {return "Please enter valid text";} return null;}), CustomButton(width: 339, text: "lbl_subscribe".tr, margin: getMargin(top: 112), variant: ButtonVariant.OutlineBlack9000c_2, fontStyle: ButtonFontStyle.MontserratRomanSemiBold15)]))))); } 
 }
